/* Copyright (c) 2014 Intuit Inc. All rights reserved. Unauthorized reproduction is a violation of applicable law. This material contains certain confidential and proprietary information and trade secrets of Intuit Inc. *///>>built
require({cache:{"url:qbo/widgets/acl/templates/AclView.html":'\x3cdiv class\x3d"table fourOhFour"\x3e\n    \x3cdiv class\x3d"tableRow"\x3e\n        \x3cdiv class\x3d"tableCell hazardWrapper"\x3e\n            \x3cdiv class\x3d"secondary-color-sprite hazard"\x3e\x3c/div\x3e\n        \x3c/div\x3e\n        \x3cdiv class\x3d"tableCell"\x3e\n            \x3cdiv class\x3d"messageHeader"\x3e{{header}}\x3c/div\x3e\n            \x3cdiv class\x3d"messageBody"\x3e{{body}}\x3c/div\x3e\n            \x3cdiv class\x3d"messageFooter"\x3e{{footer}}\x3c/div\x3e\n        \x3c/div\x3e\n    \x3c/div\x3e\n\x3c/div\x3e',
"url:qbo/widgets/acl/templates/parts/PermissionDeniedBody.html":'\x3cdiv class\x3d"deniedContent"\x3e${nls.deny_body}\x3c/div\x3e\n\x3cdiv class\x3d"contactAdminMsg hide" data-dojo-attach-point\x3d"_contactAdminMsg"\x3e${nls.contact_admin}\x3c/div\x3e\n\x3cdiv class\x3d"deniedContent" data-dojo-attach-point\x3d"_companyAdminsInfo"\x3e\x3c/div\x3e\n'}});
define("qbo/widgets/acl/AclViewController","dojo/_base/declare dojo/_base/lang dojo/has dijit/_WidgetBase dijit/_TemplatedMixin ./AclCache qbo/services/AclService dojo/text!./templates/AclView.html dojo/text!./templates/parts/PermissionDeniedBody.html dojo/i18n!qbo/nls/Acl".split(" "),function(e,f,g,h,k,d,l,c,m,a){return e([h,k],{config:{defaultConfig:{offTemplate:c.replace("{{header}}",a.default_header).replace("{{body}}","").replace("{{footer}}","")},46:{reroute:"upgradepurchaseorders",sku_feature_id:42,
offTemplate:c.replace("{{header}}",a.default_header).replace("{{body}}",a.po_turned_off_body).replace("{{footer}}",f.replace(a.po_turned_off_footer,{settingsLink:qbo.useNewSettings?"settings?pageName\x3dExpenses":"preferences?which\x3duse_purchase_orders",settingsName:qbo.useNewSettings?a.page_settings:a.page_preferences}))},9:{reroute:"upgradebills",sku_feature_id:10},12:{reroute:"upgradebills",sku_feature_id:10}},constructor:function(b){if(b)switch(this.nls=a,this.aclType=b.type,b.type){case "deny":this.templateString=
c.replace("{{header}}",a.deny_header).replace("{{body}}",m).replace("{{footer}}","");break;case "upgrade":this.templateString="\x3cdiv class\x3d'fourOhFour'\x3e\x3cdiv class\x3d'numeral notFound'\x3ethis is a placeholder for an iframe that points to marketing upgrade page using sku\x3d"+this.config[b.id].sku_feature_id+"\x3c/div\x3e\x3c/div\x3e";break;case "off":this.name=b.name;this.templateString=b.id&&this.config[b.id]?this.config[b.id].offTemplate||this.config.defaultConfig.offTemplate:this.config.defaultConfig.offTemplate;
break;case "mobile":this.templateString=c.replace("{{header}}",a.unavailable_mobile_header).replace("{{body}}",a.unavailable_mobile_body).replace("{{footer}}","");break;case "hide":qbo.isInternalPartner?"MAC"===g("qbo-partner")?this.templateString=c.replace("{{header}}",a.hidden_header).replace("{{body}}",a.hidden_body_mac).replace("{{footer}}",""):this.templateString=c.replace("{{header}}",a.hidden_header).replace("{{body}}",a.hidden_body_internal_partners).replace("{{footer}}",""):this.templateString=
c.replace("{{header}}",a.hidden_header).replace("{{body}}",a.hidden_body).replace("{{footer}}","");break;case "404":this.templateString=b.moved&&b.newUrl?c.replace("{{header}}",a.fourOhFour_header).replace("{{body}}",a.fourOhFour_moved_body.replace("{oldPageName}",a[b.newUrl+"_oldname"]).replace("{newPageName}","\x3ca href\x3d"+b.newUrl+"\x3e"+a[b.newUrl+"_newname"]+"\x3c/a\x3e")).replace("{{footer}}",""):c.replace("{{header}}",a.fourOhFour_header).replace("{{body}}",a.fourOhFour_body).replace("{{footer}}",
"");break;default:this.templateString=this.config.defaultConfig.offTemplate}},startup:function(){var b;this.inherited(arguments);"deny"===this.aclType&&(b=d.getCache(),!b.timeStamp||36E5<Date.now()-b.timeStamp.getTime()?(this.service=new l,this.service.getCompanyAdmins().then(function(b){this.createCompanyAdminsTable(b);d.setCache({data:b,timeStamp:new Date})}.bind(this),function(b){console.error(b)})):this.createCompanyAdminsTable(b.data));this.emit("page-ready")},createCompanyAdminsTable:function(b){var a=
"",c;if(Array.isArray(b)){for(c=0;c<b.length;c++)a+="\x3cdiv\x3e"+b[c].name,b[c].email&&(a+=" (\x3ca href\x3d'mailto:"+b[c].email+"'\x3e"+b[c].email+"\x3c/a\x3e)"),a+="\x3c/div\x3e";this._contactAdminMsg.classList.remove("hide");this._companyAdminsInfo.innerHTML=a}}})});
//@ sourceMappingURL=AclViewController.js.map