/* Copyright (c) 2014 Intuit Inc. All rights reserved. Unauthorized reproduction is a violation of applicable law. This material contains certain confidential and proprietary information and trade secrets of Intuit Inc. *///>>built
define("qbo/base/navigateApp",["qbo/lists/util","neo/util/common"],function(f,g){return{navigate:function(d,b,c){var e;d=d.toLowerCase();if(-1<"customer vendor employee account item term klass location paymentmethod".split(" ").indexOf(d)&&("employee"!==d||!qbo.sku.isPayrollSku))f.requireDialogViewController(d,function(a){e={};b&&(e.id=b);a.show(e)}.bind(this));else return(d=this._getNavigateUrl(d,b,c,!1))?(g.route(d),!0):!1;return!0},getNavigateUrl:function(d,b,c){return this._getNavigateUrl(d,b,
c,!0)},_getNavigateUrl:function(d,b,c,e){var a=null;d="number"===typeof d?d.toString():d;b="number"===typeof b?b.toString():b;c||(c="");switch(d){case "namedetail":a="namedetail?nameId\x3d"+b+c;break;case "register":a="register?"+c;break;case "printchecks":a="printchecks?"+c;break;case "reconcile":a="reconcile?"+c;break;case "customerdetail":a="customerdetail?nameId\x3d"+b+c;break;case "vendordetail":a="vendordetail?nameId\x3d"+b+c;break;case "creditcardexpense":case "credit card expense":case "creditcardcharge":case "1":a=
"creditcardexpense?txnId\x3d"+b+c;break;case "invoice":case "4":a="invoice?txnId\x3d"+b+c;break;case "bill":case "9":a="bill?txnId\x3d"+b+c;break;case "transfer":case "26":a="transfer?txnId\x3d"+b+c;break;case "check":case "3":a="check?txnId\x3d"+b+c;break;case "sales receipt":case "32":a="salesreceipt?txnId\x3d"+b+c;break;case "estimate":case "35":a="estimate?txnId\x3d"+b+c;break;case "charge":case "creditcardcharge":case "25":a="nonpostingcharge?txnId\x3d"+b+c;break;case "receivepayment":case "payment":case "7":a=
"recvpayment?txnId\x3d"+b+c;break;case "journal":case "journalentry":case "journal entry":case "8":a="journal?txnId\x3d"+b+c;break;case "deposit":case "27":a="deposit?txnId\x3d"+b+c;break;case "statement":case "28":a="legacy?page\x3dviewtxn\x26transactiontype\x3d28\x26transactionid\x3d"+b+c;break;case "purchase order":case "46":a="purchaseorder?txnId\x3d"+b+c;break;case "credit card credit":case "cc-credit":case "creditcardcredit":case "11":a="creditcardcredit?txnId\x3d"+b+c;break;case "vendorcredit":case "vendor credit":case "12":a=
"vendorcredit?txnId\x3d"+b+c;break;case "credit":case "13":a="nonpostingcredit?txnId\x3d"+b+c;break;case "billpaymentcheck":case "bill payment":case "bill payment (check)":case "bill payment (credit card)":case "14":case "15":a="billpayment?txnId\x3d"+b+c;break;case "cash":case "cashexpense":case "31":a="cashexpense?txnId\x3d"+b+c;break;case "job":case "53":a="job?txnId\x3d"+b+c;break;case "expense":case "54":a="expense?txnId\x3d"+b+c;break;case "billableexpense":case "billable expense charge":case "29":a=
"billableexpense?txnId\x3d"+b+c;break;case "creditmemo":case "credit memo":case "33":a="creditmemo?txnId\x3d"+b+c;break;case "refundreceipt":case "refund receipt":case "refund":case "34":a="refundreceipt?txnId\x3d"+b+c;break;case "inventory qty adjust":case "45":a="legacy?page\x3dviewtxn\x26transactiontype\x3d45\x26transactionid\x3d"+b+c;break;case "customercenter":a="customers";break;case "vendorcenter":a="vendors";break;case "memorizedtemplate":a="recurring?"+b+c;break;case "homepage":a="homepage";
break;case "timetracking":a="timeactivity?t\x3ds\x26id\x3d"+b+c;break;case "time charge":case "30":a="timeactivity?t\x3ds\x26txnId\x3d"+b+c;break;case "reconcile_account":a="reconcile";break;case "sales tax payment":case "51":a="salestaxpayment?txnId\x3d"+b+c;break;case "salestaxadjustment":case "sales tax adjustment":case "52":a="salestaxadjustment?txnId\x3d"+b+c;break;case "paycheck":case "payroll check":case "20":case "47":a="viewpaycheck?txnId\x3d"+b+c;break;case "tax payment":case "48":a="viewtaxpayment?txnId\x3d"+
b+c;break;case "payroll adjustment":case "payroll adj":case "49":a="viewtaxadjustment?txnId\x3d"+b+c;break;case "payroll refund":case "50":a="viewpayrollrefund?txnId\x3d"+b+c;break;case "itemlist":case "items":a="items";break;case "chartofaccounts":a="chartofaccounts";break;case "employee":a="employees?nameId\x3d"+b+c;break;case "55":a="partialcutransfer?txnId\x3d"+b+c;break;case "56":a="defercutransfer?txnId\x3d"+b+c;break;case "57":a="reversecutransfer?txnId\x3d"+b+c;break;case "58":a="refundcutransfer?txnId\x3d"+
b+c;break;case "59":a="grossadjustment?txnId\x3d"+b+c}return e?"/app/"+a:a}}});
//@ sourceMappingURL=navigateApp.js.map